---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: virtio-win-iso
  namespace: {{ win2016_vm_namespace }}
spec:
  source:
    http:
      url: {{ win2016_vm_virtio_url }}
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: {{ win2016_vm_virtio_size }}
    storageClassName: {{ win2016_vm_storage_class }}
    volumeMode: Filesystem
