---
- name: Template out ESO Helm values to temp dir
  template:
    src: eso-helm-chart-values.yaml
    dest: "{{ temp_dir_path }}/eso-values.yaml"

- name: Add External Secrets Helm repository
  shell:
    cmd: |-
      helm repo add external-secrets {{ eso_chart_repo }}
  changed_when: false
  failed_when: false

- name: Update Helm external-secrets repositories
  shell:
    cmd: |-
      helm repo update external-secrets
  changed_when: false

- name: Generate External Secrets Operator manifests using helm template
  shell: |
    helm template {{ eso_chart_name }} external-secrets/{{ eso_chart_name }} \
      --version {{ eso_chart_version }} \
      --namespace {{ eso_namespace }} \
      --values {{ temp_dir_path }}/eso-values.yaml \
      --include-crds
  register: helm_template_command

- name: write output manifests for helm template
  copy:
    content: "{{ helm_template_command.stdout }}"
    dest: "{{ output_dir_path }}/external-secrets-operator-helm-manifests.yaml"
