---
- name: install zfs repo
  yum:
    name: http://download.zfsonlinux.org/epel/zfs-release.el7_3.noarch.rpm
    state: present

- name: disable default broken zfs repo
  ini_file:
    path: /etc/yum.repos.d/zfs.repo
    section: zfs
    option: enabled
    value: 0

- name: enable kmod zfs repo
  ini_file:
    path: /etc/yum.repos.d/zfs.repo
    section: zfs-kmod
    option: enabled
    value: 1

- name: install zfs
  yum:
    name: zfs
    state: present

- name: ensure rc.modules exists
  file:
    state: touch
    path: /etc/rc.modules
    mode: 0755
  check_mode: no

- name: update rc.modules with zfs
  lineinfile:
    path: /etc/rc.modules
    line: 'modprobe zfs'
