---
- name: Include lib-terraria library role
  include_role:
    name: lib-terraria
  vars:
    terraria_instance_name: "{{ terraria1_instance_name }}"
    terraria_namespace: "{{ terraria1_namespace }}"
    terraria_image: "{{ terraria1_image }}"
    terraria_image_pull_policy: "{{ terraria1_image_pull_policy }}"
    terraria_game_port: "{{ terraria1_game_port }}"
    terraria_service_type: "{{ terraria1_service_type }}"
    terraria_service_annotations: "{{ terraria1_service_annotations }}"
    terraria_load_balancer_ip: "{{ terraria1_load_balancer_ip | default(omit) }}"
    terraria_storage_class: "{{ terraria1_storage_class }}"
    terraria_data_storage_size: "{{ terraria1_data_storage_size }}"
    terraria_resources: "{{ terraria1_resources }}"
    terraria_node_selector: "{{ terraria1_node_selector }}"
    terraria_tolerations: "{{ terraria1_tolerations }}"
    terraria_uid: "{{ terraria1_uid }}"
    terraria_gid: "{{ terraria1_gid }}"
    terraria_world_name: "{{ terraria1_world_name }}"
    terraria_world_size: "{{ terraria1_world_size }}"
    terraria_world_seed: "{{ terraria1_world_seed }}"
    terraria_difficulty: "{{ terraria1_difficulty }}"
    terraria_max_players: "{{ terraria1_max_players }}"
    terraria_motd: "{{ terraria1_motd }}"
    terraria_secure: "{{ terraria1_secure }}"
    terraria_npcstream: "{{ terraria1_npcstream }}"
    terraria_language: "{{ terraria1_language }}"
    terraria_autodownload: "{{ terraria1_autodownload }}"
    terraria_enabledmods: "{{ terraria1_enabledmods }}"
    terraria_autosave_interval: "{{ terraria1_autosave_interval }}"
    terraria_shutdown_message: "{{ terraria1_shutdown_message }}"
    terraria_server_pass: "{{ terraria1_server_pass }}"
    terraria_set_statefulset_zero: "{{ terraria1_set_statefulset_zero }}"
