---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-rawfile
provisioner: rawfile.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  fsType: ext4

# Only provision volumes on nodes with TPM encryption
allowedTopologies:
- matchLabelExpressions:
  - key: encryption.talos.dev/tpm
    values:
    - "true"
