---
- name: Template out kubernetes-secret-generator Helm values to temp dir
  template:
    src: ksg-helm-chart-values.yaml
    dest: "{{ temp_dir_path }}/ksg-values.yaml"

- name: Add mittwald Helm repository
  shell:
    cmd: |-
      helm repo add mittwald {{ ksg_chart_repo }}
  changed_when: false
  failed_when: false

- name: Update Helm mittwald repositories
  shell:
    cmd: |-
      helm repo update mittwald
  changed_when: false

- name: Generate kubernetes-secret-generator manifests using helm template
  shell:
    cmd: |-
      helm template kubernetes-secret-generator mittwald/{{ ksg_chart_name }} \
        --version {{ ksg_chart_version }} \
        --namespace {{ ksg_namespace }} \
        --values {{ temp_dir_path }}/ksg-values.yaml \
        --include-crds
  register: helm_template_command

- name: write output manifests for helm template
  copy:
    content: "{{ helm_template_command.stdout | harbor_rewrite_images(harbor_registry_map) if harbor_proxy_images_enabled | default(false) else helm_template_command.stdout }}"
    dest: "{{ output_dir_path }}/kubernetes-secret-generator-helm-manifests.yaml"
