---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: {{ plex_namespace }}
  labels:
    app: plex
spec:
  type: LoadBalancer
  loadBalancerIP: {{ plex_load_balancer_ip }}
  selector:
    app: plex
  ports:
    - name: pms-web
      port: 32400
      targetPort: 32400
      protocol: TCP
    - name: dlna-tcp
      port: 32469
      targetPort: 32469
      protocol: TCP
    - name: dlna-udp
      port: 1900
      targetPort: 1900
      protocol: UDP
    - name: plex-companion
      port: 3005
      targetPort: 3005
      protocol: TCP
    - name: discovery-udp
      port: 5353
      targetPort: 5353
      protocol: UDP
    - name: plex-roku
      port: 8324
      targetPort: 8324
      protocol: TCP
    - name: gdm-32410
      port: 32410
      targetPort: 32410
      protocol: UDP
    - name: gdm-32412
      port: 32412
      targetPort: 32412
      protocol: UDP
    - name: gdm-32413
      port: 32413
      targetPort: 32413
      protocol: UDP
    - name: gdm-32414
      port: 32414
      targetPort: 32414
      protocol: UDP
