version: "3.7"
services:
  unifi_video:
    image: pducharme/unifi-video-controller
    ports:
      - "10001:10001"
      - "1935:1935"
      - "6666:6666"
      - "7080:7080"
      - "7442:7442"
      - "7443:7443"
      - "7444:7444"
      - "7445:7445"
      - "7446:7446"
      - "7447:7447"
    environment:
      - TZ=America/New_York
      - PUID=2021
      - PGID=2021
      - DEBUG=1
    volumes:
      - "/docker/unifi_video_config:/var/lib/unifi-video:Z"
      - "/docker/unifi_video:/var/lib/unifi-video/videos:Z"
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
