---
name: intel-gpu-plugin

sharedDevNum: {{ intel_gpu_shared_dev_num }}
logLevel: {{ intel_gpu_log_level }}
enableMonitoring: {{ intel_gpu_enable_monitoring | lower }}
allocationPolicy: "{{ intel_gpu_allocation_policy }}"
nodeFeatureRule: {{ intel_gpu_node_feature_rule | lower }}

nodeSelector:
{{ intel_gpu_node_selector | to_nice_yaml(indent=2) | indent(2, first=true) }}
tolerations: []
