---
- name: render cilium helm chart values file
  template:
    src: cilium-values.yaml
    dest: "{{ temp_dir }}/cilium-values.yaml"
    backup: yes

- name: add cilium helm repo
  shell:
    cmd: |-
      helm repo add cilium https://helm.cilium.io/

- name: add cilium helm repo
  shell:
    cmd: |-
      helm repo update cilium

- name: run helm install for cilium
  shell:
    cmd: |-
      helm upgrade \
        cilium \
          cilium/cilium \
            --install \
            --version 1.18.5 \
            --namespace kube-system \
            --values "{{ temp_dir }}/cilium-values.yaml"
