---
talos_enable_luks: false
talos_use_tpm: false
talos_enable_kubevirt: true

talos_image_requirements:
  secureboot: true
  version: "v1.13.2"
  extensions: ["bnx2-bnx2x", "intel-ucode"]

talos_install_disk: sda
