---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: velero-nfs-backup
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/component: backup-storage
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: {{ velero_nfs_server }}
    path: {{ velero_nfs_path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velero-nfs-backup
  namespace: {{ velero_namespace }}
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/component: backup-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: velero-nfs-backup
  resources:
    requests:
      storage: 100Gi
