---
- name: Template out namespace manifest
  template:
    src: namespace.yaml
    dest: "{{ output_dir_path }}/namespace.yaml"

- name: Template out NFS StorageClass for Harbor registry
  template:
    src: nfs-storageclass.yaml
    dest: "{{ output_dir_path }}/nfs-storageclass.yaml"

- name: Template out NFS PersistentVolume for Harbor registry
  template:
    src: registry-nfs-pv.yaml
    dest: "{{ output_dir_path }}/registry-nfs-pv.yaml"

- name: Template out Harbor admin StringSecret
  template:
    src: harbor-admin-stringsecret.yaml
    dest: "{{ output_dir_path }}/harbor-admin-stringsecret.yaml"

- name: Include redis tasks
  include_tasks: redis.yml

- name: Include postgres tasks
  include_tasks: postgres.yml

- name: Include harbor tasks
  include_tasks: harbor.yml
