---
- name: Template out namespace manifest
  template:
    src: namespace.yaml
    dest: "{{ output_dir_path }}/namespace.yaml"

- name: Include redis tasks
  include_tasks: redis.yml

- name: Include postgres tasks
  include_tasks: postgres.yml

- name: Include harbor tasks
  include_tasks: harbor.yml
