---
apiVersion: v1
kind: Secret
metadata:
  name: server-password
  namespace: {{ zomboid_namespace }}
  labels:
    app: zomboid
    app.kubernetes.io/name: zomboid
    app.kubernetes.io/instance: {{ zomboid_instance_name }}
type: Opaque
stringData:
  admin-password: "{{ zomboid_admin_password }}"
  rcon-password: "{{ zomboid_rcon_password }}"
  server-password: "{{ zomboid_server_password }}"
