---
- name: show ansible_board_name
  debug:
    var: ansible_board_name

- name: Install lm-sensors
  ansible.builtin.apt:
    name: lm-sensors
    state: present

- name: Uncomment sensor modules in /etc/modules if commented out
  ansible.builtin.replace:
    path: /etc/modules
    regexp: '^#\s*{{ item }}\s*$'
    replace: '{{ item }}'
  loop: "{{ sensor_module_map[ansible_board_name] | default([]) }}"

- name: Ensure sensor modules in /etc/modules
  ansible.builtin.lineinfile:
    path: /etc/modules
    line: "{{ item }}"
    insertafter: EOF
  loop: "{{ sensor_module_map[ansible_board_name] | default([]) }}"

- name: Load sensor modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ sensor_module_map[ansible_board_name] | default([]) }}"
