#jinja2:variable_start_string:'[%', variable_end_string:'%]'
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replace-ingress-domain
  annotations:
    policies.kyverno.io/title: Replace Ingress Domain Placeholder
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Replaces [% kyverno_domain_placeholder %] with [% kyverno_domain_actual %] in all Ingress host fields.
spec:
  background: false
  rules:
    - name: replace-domain-in-rules
      match:
        any:
          - resources:
              kinds:
                - Ingress
      mutate:
        foreach:
          - list: "request.object.spec.rules"
            patchesJson6902: |-
              - path: /spec/rules/{{ elementIndex }}/host
                op: replace
                value: "{{ regex_replace_all('[% kyverno_domain_placeholder %]', '{{ element.host }}', '[% kyverno_domain_actual %]') }}"
    - name: replace-domain-in-tls
      match:
        any:
          - resources:
              kinds:
                - Ingress
      mutate:
        foreach:
          - list: "request.object.spec.tls[]"
            foreach:
              - list: "element.hosts"
                patchesJson6902: |-
                  - path: /spec/tls/{{ elementIndex0 }}/hosts/{{ elementIndex1 }}
                    op: replace
                    value: "{{ regex_replace_all('[% kyverno_domain_placeholder %]', '{{ element }}', '[% kyverno_domain_actual %]') }}"
    - name: replace-domain-in-configmaps
      match:
        any:
          - resources:
              kinds:
                - ConfigMap
              namespaces:
                - harbor
      mutate:
        foreach:
          - list: "request.object.data | keys(@)"
            patchesJson6902: |-
              - path: /data/{{ element }}
                op: replace
                value: "{{ regex_replace_all('[% kyverno_domain_placeholder %]', '{{ request.object.data.\"{{ element }}\" }}', '[% kyverno_domain_actual %]') }}"
