# Kyverno Helm values
admissionController:
  replicas: {{ kyverno_admission_controller_replicas }}

backgroundController:
  replicas: {{ kyverno_background_controller_replicas }}

cleanupController:
  replicas: {{ kyverno_cleanup_controller_replicas }}

reportsController:
  replicas: {{ kyverno_reports_controller_replicas }}
