---
- name: add coredns helm repository
  shell:
    cmd: |
      helm repo add coredns {{ coredns_repo_url }}
      helm repo update

- name: create coredns-external namespace
  shell:
    cmd: |-
      kubectl create namespace {{ coredns_external_namespace }} \
        --kubeconfig {{ kubeconfig_path }} \
        --dry-run=client -o yaml | kubectl apply --kubeconfig {{ kubeconfig_path }} -f -

- name: render coredns values file
  template:
    src: coredns-values.yaml
    dest: "{{ temp_dir }}/coredns-external-values.yaml"

- name: install coredns via helm
  shell:
    cmd: |-
      helm upgrade \
        coredns-external \
          coredns/coredns \
            --kubeconfig {{ kubeconfig_path }} \
            --install \
            --version {{ coredns_chart_version }} \
            --namespace {{ coredns_external_namespace }} \
            --values "{{ temp_dir }}/coredns-external-values.yaml"
