---
apiVersion: v1
kind: Secret
metadata:
  name: server-password
  namespace: {{ valheim_namespace }}
  labels:
    app: valheim
    app.kubernetes.io/name: valheim
    app.kubernetes.io/instance: {{ valheim_instance_name }}
type: Opaque
stringData:
  server-pass: "{{ valheim_server_pass }}"
