---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-postgres-tls
  namespace: harbor
spec:
  secretName: harbor-postgres-tls
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: harbor-postgres-pg-db-pgbouncer.harbor.svc
  dnsNames:
    - harbor-postgres-pg-db-pgbouncer
    - harbor-postgres-pg-db-pgbouncer.harbor
    - harbor-postgres-pg-db-pgbouncer.harbor.svc
    - harbor-postgres-pg-db-pgbouncer.harbor.svc.cluster.local
    - harbor-postgres-pg-db-primary
    - harbor-postgres-pg-db-primary.harbor
    - harbor-postgres-pg-db-primary.harbor.svc
    - harbor-postgres-pg-db-primary.harbor.svc.cluster.local
    - "*.harbor-postgres-pg-db-pods.harbor.svc.cluster.local"
  usages:
    - server auth
    - client auth
