---
- name: template out configs
  dest: "{{ temp_dir }}/{{ item }}"
  loop:
    - smtp-proxy-configmap.yaml
    - smtp-proxy-service.yaml
    - smtp-proxy-statefulset.yaml

- name: apply configs
  loop:
    - smtp-proxy-configmap.yaml
    - smtp-proxy-service.yaml
    - smtp-proxy-statefulset.yaml
