---
- name: Copy KubeVirt operator manifest (with namespace labels)
  copy:
    content: "{{ lookup('file', role_path + '/files/kubevirt-operator.' + kubevirt_version + '.yaml') | patch_namespace_labels(kubevirt_namespace_extra_labels) }}"
    dest: "{{ output_dir_path }}/kubevirt-operator.yaml"

- name: Template out KubeVirt CR
  template:
    src: kubevirt-cr.yaml
    dest: "{{ output_dir_path }}/kubevirt-cr.yaml"
