---
apiVersion: v1
kind: Secret
metadata:
  name: godaddy-config
  namespace: godaddy-ddns
type: Opaque
stringData:
  godaddy-ddns.conf: |
    example.com
    --key
    YOUR_GODADDY_API_KEY
    --secret
    YOUR_GODADDY_API_SECRET
