---
apiVersion: v1
kind: Secret
metadata:
  name: godaddy-config
  namespace: godaddy-ddns
type: Opaque
stringData:
  GODADDY_DOMAIN: "example.com"
  GODADDY_API_KEY: "YOUR_GODADDY_API_KEY"
  GODADDY_API_SECRET: "YOUR_GODADDY_API_SECRET"
