---
apiVersion: v1alpha1
kind: VolumeConfig
name: STATE
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm:
        checkSecurebootStatusOnEnroll: true
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
encryption:
  provider: luks2
  keys:
    - slot: 0
      tpm:
        checkSecurebootStatusOnEnroll: true
      lockToState: false
    - slot: 1
      static:
        passphrase: {{ talos_luks_passphrase }}
