---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-proxy-config
  namespace: {{ shinobi_smtp_proxy_namespace }}
data:
  config.yaml: |-
    {{ lookup('template', 'smtp-proxy-config.yaml.j2') | indent(4, False) }}
