---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: smtp-proxy
  namespace: {{ shinobi_smtp_proxy_namespace }}
  labels:
    app: smtp-proxy
spec:
  selector:
    matchLabels:
      app: smtp-proxy
  podMetricsEndpoints:
    - port: health
      path: /metrics
      interval: 15s
