---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-proxy-camera-creds
  namespace: {{ shinobi_smtp_proxy_namespace }}
type: Opaque
stringData:
  camera-username: "{{ shinobi_smtp_proxy_camera_username }}"
  camera-password: "{{ shinobi_smtp_proxy_camera_password }}"
