---
# CoreDNS External configuration - override in group_vars with vault
coredns_external_namespace: coredns-external
#coredns_external_dns_domain: CHANGEME
#coredns_external_loadbalancer_ip: CHANGEME

# Helm chart versions
coredns_chart_version: "1.45.0"

# Helm repositories
coredns_repo_url: "https://coredns.github.io/helm"
