---
apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  forceRegenerate: false
  data:
    admin-user: "admin"
  fields:
    - fieldName: "admin-password"
      encoding: "base64"
      length: "32"
