---
- name: Template out namespace manifest
  template:
    src: namespace.yaml
    dest: "{{ output_dir_path }}/namespace.yaml"

- name: Template out mongo-tools helper pod
  template:
    src: mongo-tools-pod.yaml
    dest: "{{ output_dir_path }}/mongo-tools-pod.yaml"

- name: Include MongoDB tasks
  include_tasks: mongodb.yml

- name: Include Unifi tasks
  include_tasks: unifi.yml
