---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: {{ palworld_namespace }}
  labels:
    app: palworld
    app.kubernetes.io/name: palworld
    app.kubernetes.io/instance: {{ palworld_instance_name }}
data:
  config.yaml: |
    ---
{% for key, value in palworld_server_config.items() %}
    {{ key }}: {{ value }}
{% endfor %}
