---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ palworld_instance_name }}
  namespace: {{ palworld_namespace }}
  labels:
    app: palworld
    app.kubernetes.io/name: palworld
    app.kubernetes.io/instance: {{ palworld_instance_name }}
