---
apiVersion: v1
kind: Secret
metadata:
  name: server-password
  namespace: {{ palworld_namespace }}
  labels:
    app: palworld
    app.kubernetes.io/name: palworld
    app.kubernetes.io/instance: {{ palworld_instance_name }}
type: Opaque
stringData:
  server-password: "{{ palworld_server_password }}"
  admin-password: "{{ palworld_admin_password }}"
