---
apiVersion: v1
kind: Secret
metadata:
  name: server-password
  namespace: {{ terraria_namespace }}
  labels:
    app: terraria
    app.kubernetes.io/name: terraria
    app.kubernetes.io/instance: {{ terraria_instance_name }}
type: Opaque
stringData:
  server-pass: "{{ terraria_server_pass }}"
