---
- name: autofs | install luks keys
  copy:
    src: "{{ item }}"
    dest: "/etc/.keys/{{ item }}"
  with_items:
    - "sbay1.key"
    - "sbay2.key"
    - "sbay3.key"
    - "sbay4.key"
    - "sbay5.key"
    - "sbay6.key"
    - "sgbak0.key"
    - "zusb0.key"
    - "zusb1.key"
    - "zusb2.key"
    - "zusb3.key"

- name: autofs | configure auto.master
  lineinefile:
    src: "/etc/auto.master"
    regexp: "^\/media\/crypt"
    line: "/media/crypt    /etc/auto.luks --timeout=300"

- name: autofs | configure auto.luks
  copy:
    src: auto.luks
    dest: /etc/auto.luks
