---
- name: mounts | create docker folder
  file:
    state: directory
    path: "/docker"

- name: mounts | create unifi_video folder
  file:
    state: directory
    path: "/docker/unifi_video"
    owner: unifi_video
    group: unifi_video

- name: mounts | register mount options
  set_fact:
    unifi_video_mount_options:
      - 'rw'
      - 'relatime'
      - 'vers=4'
#      - 'rsize=1048576'
#      - 'wsize=1048576'
#      - 'namlen=255'
      - 'hard'
      - 'proto=tcp'
#      - 'timeo=600'
#      - 'retrans=2'
#      - 'sec=sys'
#      - 'mountaddr=192.168.2.73'
#      - 'mountvers=4'
#      - 'mountport=20048'
#      - 'mountproto=udp'
#      - 'local_lock=none'
#      - 'addr=192.168.1.73'

- name: mounts | mount unifi_video
  mount:
    fstype: 'nfs'
    path: '/docker/unifi_video'
    opts: "{{ unifi_video_mount_options | join(',') }}"
    src: '{{ nfs_server_ip }}:/volume1/unifi_video'
    state: 'mounted'
