---
apiVersion: v1
kind: Secret
metadata:
  name: godaddy-config
  namespace: {{ godaddy_ddns_namespace }}
type: Opaque
stringData:
  godaddy-ddns.conf: |
    {{ godaddy_ddns_domain }}
    --key
    {{ godaddy_ddns_api_key }}
    --secret
    {{ godaddy_ddns_api_secret }}
