---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: godaddy-ddns
  namespace: {{ godaddy_ddns_namespace }}
spec:
  schedule: "{{ godaddy_ddns_schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ godaddy_ddns_successful_jobs_history }}
  failedJobsHistoryLimit: {{ godaddy_ddns_failed_jobs_history }}
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: godaddy-ddns
        spec:
          restartPolicy: Never
          containers:
            - name: app
              image: {{ godaddy_ddns_image }}
              args:
                - "%/godaddy-ddns.config/godaddy-ddns.conf"
              volumeMounts:
                - name: godaddy-config
                  mountPath: /godaddy-ddns.config
                  readOnly: true
              resources:
                requests:
                  cpu: "{{ godaddy_ddns_resources_requests_cpu }}"
                  memory: "{{ godaddy_ddns_resources_requests_memory }}"
                limits:
                  cpu: "{{ godaddy_ddns_resources_limits_cpu }}"
                  memory: "{{ godaddy_ddns_resources_limits_memory }}"
          volumes:
            - name: godaddy-config
              secret:
                secretName: godaddy-config
