---
apiVersion: v1
kind: Secret
metadata:
  name: godaddy-config
  namespace: {{ godaddy_ddns_namespace }}
type: Opaque
stringData:
  GODADDY_DOMAIN: "{{ godaddy_ddns_domain }}"
  GODADDY_API_KEY: "{{ godaddy_ddns_api_key }}"
  GODADDY_API_SECRET: "{{ godaddy_ddns_api_secret }}"
