---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: godaddy-ddns
  namespace: {{ godaddy_ddns_namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: godaddy-ddns-secret-reader
  namespace: {{ godaddy_ddns_namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["godaddy-config"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: godaddy-ddns-secret-reader
  namespace: {{ godaddy_ddns_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: godaddy-ddns-secret-reader
subjects:
  - kind: ServiceAccount
    name: godaddy-ddns
    namespace: {{ godaddy_ddns_namespace }}
