---
apiVersion: v1
kind: Secret
metadata:
  name: {{ vscode_instance_name }}-ssh-keys
  namespace: {{ vscode_namespace }}
  labels:
    app.kubernetes.io/name: vscode-remote
    app.kubernetes.io/instance: {{ vscode_instance_name }}
type: Opaque
stringData:
  authorized_keys: |
{% for key in vscode_ssh_authorized_keys %}
    {{ key }}
{% endfor %}
