---
- name: Configure Harbor pull-through cache projects
  hosts: localhost
  gather_facts: no
  vars:
    cluster_name: k8s2

  tasks:
    - name: set repo_dir for subdirectory playbook
      set_fact:
        repo_dir: "{{ (playbook_dir ~ '/../../..') | realpath }}"

    - name: include tasks/1_set_vars.yml
      include_tasks: "{{ playbook_dir }}/../../tasks/1_set_vars.yml"

    - name: Include harbor registry vars
      include_vars: "{{ repo_dir }}/ansible/inventory/group_vars/cluster/harbor_registry.yml"

    - name: Configure pull-through cache projects
      include_role:
        name: lib-harbor-pull-through-project
