---
- name: Configure Harbor pull-through cache projects
  hosts: localhost
  gather_facts: no
  vars:
    cluster_name: k8s2

  tasks:
    - name: Include cluster vars
      include_vars: "../../inventory/group_vars/cluster/{{ cluster_name }}.yml"

    - name: Include harbor registry vars
      include_vars: "../../inventory/group_vars/cluster/harbor_registry.yml"

    - name: Configure pull-through cache projects
      include_role:
        name: lib-harbor-pull-through-project
