---
- name: Include lib-vscode-remote-statefulset library role
  include_role:
    name: lib-vscode-remote-statefulset
  vars:
    vscode_instance_name: "{{ vscode_instance_name }}"
    vscode_namespace: "{{ vscode_namespace }}"
    vscode_image: "{{ vscode_image }}"
    vscode_image_pull_policy: "{{ vscode_image_pull_policy }}"
    vscode_ssh_port: "{{ vscode_ssh_port }}"
    vscode_ssh_authorized_keys: "{{ vscode_ssh_authorized_keys }}"
    vscode_service_type: "{{ vscode_service_type }}"
    vscode_service_load_balancer_ip: "{{ vscode_service_load_balancer_ip }}"
    vscode_service_annotations: "{{ vscode_service_annotations }}"
    vscode_storage_class: "{{ vscode_storage_class }}"
    vscode_storage_size: "{{ vscode_storage_size }}"
    vscode_home_size: "{{ vscode_home_size }}"
    vscode_resources: "{{ vscode_resources }}"
    vscode_node_selector: "{{ vscode_node_selector }}"
    vscode_tolerations: "{{ vscode_tolerations }}"
    vscode_env_vars: "{{ vscode_env_vars }}"
    output_dir_path: "{{ output_dir_path }}"
