---
- name: ensure nic enp3s4f0 is set to come up on boot
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-enp3s4f0
    regexp: '^ONBOOT'
    line: 'ONBOOT=yes'
- name: ensure nic enp3s4f1 is set to come up on boot
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-enp3s4f1
    regexp: '^ONBOOT'
    line: 'ONBOOT=yes'

- name: install deltarpm
  yum:
    name: deltarpm
    state: latest
- name: update
  yum:
    name: '*'
    state: latest

- name: install common tools and other deps
  yum: pkg={{item}} state=installed
  with_items:
   - lm_sensors
   - sysstat
   - iotop
   - screen
   - docker
   - docker-python
   - unzip
   - kernel-devel
   - sdparm
   - nfs-utils
   - lsof

- include: nic_team.yml
