---
- name: install systemd mounts
  template:
    src: templates/nfs_mount_template.mount
    dest: "/etc/systemd/system/{{ item.name_safe }}"
    owner: root
    group: root
    mode: '0755'
  loop: "{{ list_of_mounts }}"

- name: reload systemd units
  systemd:
    daemon_reexec: yes

- name: enable mount
  systemd:
    name: "{{ item.name_safe }}"
    enabled: yes
    state: started
  loop: "{{ list_of_mounts }}"
