---
- name: install nmcli deps
  yum: pkg={{item}} state=installed
  with_items:
   - epel-release
   - NetworkManager-glib-devel
   - libnm-gtk-devel
   - nm-connection-editor
   - libsemanage-python
   - policycoreutils-python

- name: try nmcli add team - conn_name only & ip4 gw4
  nmcli:
    type: team
    conn_name: '{{ item.conn_name }}'
    ip4: '{{ item.ip4 }}'
    gw4: '{{ item.gw4 }}'
    dns4: '8.8.8.8'
    state: present
  with_items:
    - '{{ nmcli_team }}'

- name: try nmcli add teams-slave
  nmcli:
    type: team-slave
    conn_name: '{{ item.conn_name }}'
    ifname: '{{ item.ifname }}'
    master: '{{ item.master }}'
    state: present
  with_items:
    - '{{ nmcli_team_slave }}'

- name: up primary team
  shell: nmcli c up team0
