---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-proxy-config
  namespace: shinobi
data:
  config.yaml: |-
    {{ lookup('file', '../files/smtp-proxy-config.yaml') | indent(4, False) }}

  requirements.txt: |-
    {{ lookup('file', '../files/requirements.txt') | indent(4, False) }}

  smtp-proxy.py: |-
    {{ lookup('file', '../files/smtp-proxy.py') | indent(4, False) }}
