---
- name: container | create /etc/docker/compose folder
  file:
    state: directory
    owner: root
    group: root
    path: /etc/docker/compose

- name: "container | create /etc/docker/compose/{{ service_name }} folder"
  file:
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    path: "/etc/docker/compose/{{ service_name }}"

- name: container | copy service files
  copy:
    src: "./elk_files/"
    dest: "/etc/docker/compose/{{ service_name }}/"

- name: container | install systemd unit file
  template:
    src: templates/docker_service.service
    dest: "/etc/systemd/system/{{ service_name }}.service"
    mode: 0755
    owner: root
    group: root

- name: container | reload systemd units
  systemd:
    daemon_reload: yes
