---
- name: "create {{ service_group }} group"
  group:
    name: "{{ service_group }}"
    gid: "{{ service_gid }}"
    state: present

- name: "create {{ service_user }} user"
  user:
    name: "{{ service_user }}"
    uid: "{{ service_uid }}"
    groups: "{{ service_group }},docker"
