---
- name: Add Docker-CE stable repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable Repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes

- name: Install docker-ce
  yum:
    state: installed
    pkg:
      - docker-ce
      - python-docker-py

- name: install pip
  shell:
    cmd: pip install pip setuptools -U

- name: install pip
  pip:
    name:
      - pip
      - setuptools
    state: latest
    executable: pip3

- name: install docker-compose
  pip:
    state: latest
    name: docker-compose
    executable: pip3

- name: link docker-compose
  file:
    state: link
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
