---
- name: Add Docker-CE stable repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable Repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes

- name: Install docker-ce
  yum:
    state: installed
    pkg:
      - docker-ce
      - python-docker-py

- name: install docker-compose
  pip:
    state: latest
    name: docker-compose
    executable: /usr/local/bin/pip3

- name: link docker-compose
  file:
    state: link
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose

- name: configure docker mount dependencies
  template:
    src: templates/docker.service
    dest: "/etc/systemd/system/multi-user.target.wants/docker.service"
    owner: root
    group: root
    mode: '0644'

- name: reload systemd units
  systemd:
    daemon_reexec: yes
