---
apiVersion: v1
kind: Pod
metadata:
  name: mongo-tools
  namespace: {{ unifi_namespace }}
  labels:
    app: mongo-tools
spec:
  containers:
  - name: mongo-tools
    image: mongo:7.0
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: nfs-data
      mountPath: /nfs
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  volumes:
  - name: nfs-data
    nfs:
      server: {{ unifi_backup_nfs_server }}
      path: {{ unifi_backup_nfs_path }}
  restartPolicy: Never
