---
apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  name: {{ unifi_psmdb_cluster_name }}-secrets
  namespace: {{ unifi_namespace }}
spec:
  forceRegenerate: false
  data:
    MONGODB_USER_ADMIN_USER: dXNlckFkbWlu
    MONGODB_CLUSTER_ADMIN_USER: Y2x1c3RlckFkbWlu
    MONGODB_CLUSTER_MONITOR_USER: Y2x1c3Rlck1vbml0b3I=
    MONGODB_DATABASE_ADMIN_USER: ZGF0YWJhc2VBZG1pbg==
    MONGODB_BACKUP_USER: YmFja3Vw
  fields:
    - fieldName: "MONGODB_USER_ADMIN_PASSWORD"
      encoding: "base64"
      length: "24"
    - fieldName: "MONGODB_CLUSTER_ADMIN_PASSWORD"
      encoding: "base64"
      length: "24"
    - fieldName: "MONGODB_CLUSTER_MONITOR_PASSWORD"
      encoding: "base64"
      length: "24"
    - fieldName: "MONGODB_DATABASE_ADMIN_PASSWORD"
      encoding: "base64"
      length: "24"
    - fieldName: "MONGODB_BACKUP_PASSWORD"
      encoding: "base64"
      length: "24"
