---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: unifi-data-nfs
spec:
  capacity:
    storage: {{ unifi_data_nfs_size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ unifi_nfs_storage_class }}
  nfs:
    server: {{ unifi_data_nfs_server }}
    path: {{ unifi_data_nfs_path }}
  mountOptions:
    - hard
    - nfsvers=4.1
    - noatime
