---
- name: container | create /etc/docker/compose folder
  file:
    state: directory
    owner: root
    group: root
    path: /etc/docker/compose

- name: container | create /etc/docker/compose/shinobi folder
  file:
    state: directory
    owner: shinobi
    group: shinobi
    path: /etc/docker/compose/shinobi

- name: container | copy default conf.json
  copy:
    src: conf.json
    dest: /etc/docker/compose/shinobi/conf.json
    force: no

- name: container | copy default super.json
  copy:
    src: super.json
    dest: /etc/docker/compose/shinobi/super.json
    force: no

- name: container | copy docker-compose file
  copy:
    src: docker-compose.yml
    dest: /etc/docker/compose/shinobi/docker-compose.yml

- name: container | install systemd unit file
  copy:
    src: shinobi.service
    dest: /etc/systemd/system/shinobi.service
    mode: 0755
    owner: root
    group: root

- name: container | reload systemd units
  systemd:
    daemon_reload: yes
