---
- name: container | create /etc/docker/compose folder
  file:
    state: directory
    owner: root
    group: root
    path: /etc/docker/compose

- name: container | create /etc/docker/compose/shinobi folder
  file:
    state: directory
    owner: shinobi
    group: shinobi
    path: /etc/docker/compose/shinobi

#- name: container | copy default conf.json
#  copy:
#    src: ./conf.json
#    dest: /docker/nfs_mount/shinobi/conf.json
#    force: no
#    owner: shinobi
#    group: shinobi
#    mode: 0660
#
#- name: container | copy default super.json
#  copy:
#    src: ./super.json
#    dest: /docker/nfs_mount/shinobi/super.json
#    force: no
#    owner: shinobi
#    group: shinobi
#    mode: 0660

- name: container | create shinobi_host_mount_prefix
  file:
    state: directory
    path: "{{ shinobi_host_mount_prefix }}"
    owner: shinobi
    group: shinobi

#- name: container | copy default conf.json
#  file:
#    state: directory
#    path: /docker/nfs_mount/shinobi/shinobiConfig
#    owner: shinobi
#    group: shinobi
#    mode: 0660

#- name: container | copy default conf.json
#  copy:
#    src: ./conf.json
#    dest: /docker/nfs_mount/shinobi/shinobiConfig/conf.json
#    force: no
#    owner: shinobi
#    group: shinobi
#    mode: 0660
#
#- name: container | copy default super.json
#  copy:
#    src: ./super.json
#    dest: /docker/nfs_mount/shinobi/shinobiConfig/super.json
#    force: no
#    owner: shinobi
#    group: shinobi
#    mode: 0660

# TODO: Parameterize traefik vs standalone
- name: container | copy docker-compose file
  template:
    src: docker-compose-standalone.yml
    dest: /etc/docker/compose/shinobi/docker-compose.yml
    owner: shinobi
    group: shinobi
    mode: 0644

- name: container | copy docker-entrypoint file
  copy:
    src: docker-entrypoint.sh
    dest: /etc/docker/compose/shinobi/docker-entrypoint.sh
    owner: shinobi
    group: shinobi
    mode: 0755

- name: container | install shinobi.dockerfile
  template:
    src: templates/shinobi.dockerfile
    dest: /etc/docker/compose/shinobi/shinobi.dockerfile
    owner: shinobi
    group: shinobi
    mode: 0644

- name: container | install systemd unit file
  copy:
    src: shinobi.service
    dest: /etc/systemd/system/shinobi.service
    mode: 0755
    owner: root
    group: root

- name: container | reload systemd units
  systemd:
    daemon_reload: yes
