---
- name: firewalld | copy shinobi firewalld xml file
  copy:
    content: |
      <?xml version="1.0" encoding="utf-8"?>
      <service>
        <short>shinobi</short>
        <description>shinobi</description>
        <port protocol="tcp" port="8080"/>
      </service>
    dest: /usr/lib/firewalld/services/shinobi.xml
    backup: yes
  run_once: yes

- name: firewalld | configure firewalld
  firewalld:
    zone: public
    service: shinobi
    permanent: true
    state: enabled
#  retries: 3
#  delay: 3
#  register: shinobi_firewalld_result
#  until: shinobi_result is succeeded
