version: "3.7"
services:
  traefik:
    build:
      context: .
      dockerfile: traefik.dockerfile
    container_name: traefik
#    user: "2022:2022"
    ports:
      - "8080:8080"
    environment:
      - TZ=America/New_York
      - PUID=2023
      - PGID=2023
    networks:
      - traefik
    volumes:
      - "/docker/nfs_mount/traefik/traefik_home:/var/traefik_home:Z"

# proxy:
#    dockerfile: nginx.dockerfile
#    container_name: proxy
#    restart: unless-stopped
#    ports:
#      - "4444:8080"
#    depends_on:
#      - traefik
#    networks:
#      - traefik


networks:
  traefik:
