version: '3'

services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      outside-world:
      internal-network:

networks:
 #   everything that is *only* on "internal network" cannot talk to WAN
  internal-network:
    internal: true
 #   add this network to a container to make it talk to the rest of the world
  outside-world:
