version: '3'

services:
  traefik:
    # The official v2.0 Traefik docker image
    image: traefik:v2.0
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
#      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file=true"
      - "--providers.file.filename=/traefik_dynamic.toml"
#      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
#      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`{{ ansible_nodename }}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users={{ traefik_htpasswd | string | regex_replace('\$', '$$') }}"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - "/docker/nfs_mount/traefik/letsencrypt:/letsencrypt:Z"
      - "/etc/ssl/private:/etc/ssl/private:Z"
      - "/docker/nfs_mount/traefik/traefik_dynamic.toml:/traefik_dynamic.toml"
#      - /opt/traefik/acme.json:/acme.json
    networks:
      outside-world:
      internal-network:

networks:
 #   everything that is *only* on "internal network" cannot talk to WAN
  internal-network:
    internal: true
 #   add this network to a container to make it talk to the rest of the world
  outside-world:
    external:
      name: traefik_outside-world
