---
- name: install epel
  yum:
    name: epel-release
    state: latest

- name: update
  yum:
    name: '*'
    state: latest
  when: run_updates | default(false)

- name: install common tools and other deps
  yum:
    state: installed
    pkg:
      - lm_sensors
      - sysstat
      - iotop
      - screen
      - unzip
      - kernel-devel
      - sdparm
      - nfs-utils
      - lsof
      - rsync
      - iftop
      - iperf
      - yum-utils
      - nfs4-acl-tools
      - python-pip
      - python3
      - python3-pip

#- name: including nic_team tasks
#  include_tasks: nic_team.yml

- name: upgrade pip and setuptools
  shell:
    cmd: python3 -m pip install pip setuptools -U
  register: upgrade_default_pip

#- name: upgrade pip and setuptools
#  pip:
#    name:
#      - pip
#      - setuptools
#    state: latest
#    executable: /usr/local/bin/pip3

#- name: include mounts tasks
#  include_tasks: mounts.yml
