---
- name: container | create /root/docker_unifi_video folder
  file:
    state: directory
    owner: root
    group: root
    path: /root/docker_unifi_video

- name: container | copy docker-compose file
  copy:
    src: docker-compose.yml
    dest: /root/docker_unifi_video/docker-compose.yml
