---
- name: mounts | create docker folder
  file:
    state: directory
    path: "/docker"

- name: mounts | create unifi_video folder
  file:
    state: directory
    path: "/docker/unifi_video"
    owner: unifi_video
    group: unifi_video

- name: mounts | register mount options
  set_fact:
    unifi_video_mount_options:
      - 'rw'
      - 'relatime'
      - 'vers=4'
      - 'hard'
      - 'proto=tcp'
