---
- name: container | search for existing container
  shell: 'docker ps -a --filter name=^/plex_nfs$'
  register: docker_ps_filtered
  changed_when: false
  check_mode: no

- name: container | create the docker plex_nfs container
  shell: >
    docker ps -a | grep [p]lex_nfs || \
    docker create \
      --name=plex_nfs \
      --net=host \
      --restart=always \
      -e VERSION=latest \
      -e PUID=2020 -e PGID=2020 \
      -e TZ=America/NewYork \
      -v /data/docker/plex/config:/config:Z \
      -v /docker/plex/tvshows:/data/tvshows:Z \
      -v /docker/plex/movies:/data/movies:Z \
      -v /docker/plex/audiobooks:/data/audiobooks:Z \
      -v /docker/plex/other_video:/data/other_video:Z \
      -v /docker/plex/music:/data/music:Z \
      -v /tank0/transcode:/transcode:Z \
      linuxserver/plex
  when: ( docker_ps_filtered.stdout_lines | length ) < 1
