---
- name: enable firewall for plex
  firewalld:
    port: 32400/tcp
    permanent: true
    state: enabled
- name: create plex root dir
  file:
    path: /tank/data0/plex
    state: directory
- name: create plex config dir
  file:
    path: /tank/data0/plex/config
    state: directory
- name: create plex movies dir
  file:
    path: /tank/data0/plex/movies
    state: directory
- name: create plex music dir
  file:
    path: /tank/data0/plex/music
    state: directory
- name: create plex tvshows dir
  file:
    path: /tank/data0/plex/tvshows
    state: directory
- name: create plex transcode dir
  file:
    path: /tank/data0/plex/transcode
    state: directory
- name: exports
  lineinfile:
    path: /etc/exports
    line: '/tank/data0/plex 192.168.1.0/24(rw,async,no_root_squash,no_all_squash)'

# TODO: LUKS

#  roles:
#    - role: 'marvinpinto.docker-plex'
#      docker_plex_container_name: 'plex'
#      docker_plex_version: 'latest'
#      docker_plex_mounted_directory: '/tank/data0/plex'
#      become: true

# zpool create tank raidz sdc sdd sde cache sda
# zfs create tank/data0


# TODO: create volumes in tw_cli
# TODO: create zpool, vdev's
# TODO: create L2ARC
# TODO: create plex data folders
# TODO: https://galaxy.ansible.com/marvinpinto/docker-plex/

# TODO: enable docker
# TODO: start docker
# TODO: docker create --name=plex --net=host --restart=always -e VERSION=latest -e PUID=1001 -e PGID=1001 -e TZ=America/NewYork -v /tank/data0/plex/config:/config:Z -v /tank/data0/plex/tvshows:/data/tvshows:Z -v /tank/data0/plex/movies:/data/movies:Z -v /tank/data0/plex/music:/data/music:Z -v /tank/data0/plex/transcode:/transcode:Z linuxserver/plex
# TOOD: exports /media/plex_data 192.168.1.0/24(rw,async,no_root_squash,no_all_squash)
#  - name: create docker plex container
#    docker_container:
#      name: plex
#      image: linuxserver/plex
#      volumes:
#        - /data

# TODO: Firewalld stuff (still disabled)
# TODO: enable / start nfs-server

# ssh keys

# set up raid disks

## single's

# zpool

# exports

# docker container
