---
- name: Apply ArgoCD Application manifests
  shell:
    cmd: |-
      kubectl apply \
        --kubeconfig {{ kubeconfig_path }} \
        -f {{ role_path }}/files/{{ item }}
  loop:
    - openebs-rawfile-application.yaml
    - openebs-rawfile-storageclass-application.yaml
    - percona-postgres-operator-application.yaml
    - redis-operator-application.yaml
