---
- hosts: nfs_master
  become: true
  tasks:
#     - include_role:
#         name: common

#
# TODO: serial_console
#    # ref: https://help.ubuntu.com/community/SerialConsoleHowto
#    - include_role:
#        name: serial_console
#

#     - include_role:
#         name: sensors
#
#     - include_role:
#        name: liquidctl
#
#     - include_role:
#        name: node_exporter


   - include_role:
       name: zfs-core


#     # TODO: disable password rotation - 5.5.1.x
#     - include_role:
#         name: UBUNTU22-CIS
#       vars:
#         ubtu22cis_rule_3_1_2: false
#         ubtu22cis_rsync_server: true
#         ubtu22cis_rpc_required: true
#         ubtu22cis_rule_5_4_2: false  # pam_faillock, but the role is broken.
#         ubtu22cis_ufw_allow_out_ports:
#           - 53
#           - 80
#           - 123
#           - 443
#         ubtu22cis_sshd:
#           log_level: "INFO"
#           max_auth_tries: 4
#           ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
#           macs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"
#           kex_algorithms: "curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"
#           client_alive_interval: 300
#           client_alive_count_max: 3
#           login_grace_time: 60
#           max_sessions: 8
#           # WARNING: make sure you understand the precedence when working with these values!!
#           allow_users: "{{ ssh_allowed_user }}"
#           allow_groups: "{{ ssh_allowed_user }}"


#    - include_role:
#        name: udev-luks-autofs
#
#    - include_role:
#        name: firewall
