---
- hosts: nfs_master
  become: true
  tasks:
    - include_role:
        name: common

#    - include_role:
#        name: nic_team
#
#    # ref: https://help.ubuntu.com/community/SerialConsoleHowto
#    - include_role:
#        name: serial_console
#
#    - include_role:
#        name: sensors
#
#    - include_role:
#        name: liquidctl
#
#    - include_role:
#        name: node_exporter
#
#    - include_role:
#        name: zfs

    - include_role:
        name: UBUNTU22-CIS
      vars:
        ubtu22cis_rule_3_1_2: false
        ubtu22cis_rsync_server: true
        ubtu22cis_rpc_required: true
        ubtu22cis_rule_5_4_2: false  # pam_faillock, but the role is broken.

#    - include_role:
#        name: udev-luks-autofs
#
#    - include_role:
#        name: firewall
