---
- name: configure nfs_master
  hosts: nfs_master
  roles:
  - role: common
  - role: tw_cli
    #    - role: wintv
    #    - role: docker
    #    - role: plex

- name: configure plex_master
  hosts: plex_master
  roles:
    - role: common
    - role: tw_cli
    - role: plex
