---
- name: configure nfs_master
  hosts: nfs_master
  become: yes
  roles:
    - role: common
    - role: tw_cli
    - role: zfs
#    - role: wintv
#    - role: docker
#    - role: plex

- name: configure plex_master
  hosts: plex_master
  become: yes
  roles:
    - role: common
    - role: tw_cli
    - role: docker
    - role: plex
