---
- name: configure unifi_docker
  hosts: unifi_docker
  become: yes
  vars:
    run_yum_update: "{{ true | bool }}"
  roles:
    - role: common
#    - role: nic_team
    - role: docker
    - role: docker_unifi_video

# TODO: systemd unit file for docker-compose
# TODO: reformat / no usb drive. Use sda instead.
