---
- name: Template out namespace manifest
  template:
    src: namespace.yaml
    dest: "{{ output_dir_path }}/namespace.yaml"

- name: Template out node-exporter namespace manifest
  template:
    src: namespace-node-exporter.yaml
    dest: "{{ output_dir_path }}/namespace-node-exporter.yaml"

- name: Template out Grafana admin StringSecret
  template:
    src: grafana-admin-stringsecret.yaml
    dest: "{{ output_dir_path }}/grafana-admin-stringsecret.yaml"

- name: Template out backups2 PrometheusRule
  template:
    src: backups2-alerts.yaml
    dest: "{{ output_dir_path }}/backups2-alerts.yaml"

- name: Include kube-prometheus-stack tasks
  include_tasks: kube-prometheus-stack.yml
