---
apiVersion: v1
kind: Secret
metadata:
  name: alerta-secrets
  namespace: {{ alerta_namespace }}
type: Opaque
stringData:
  ALERTA_API_KEY: "{{ alerta_admin_api_key }}"
  DISCORD_WEBHOOK_URL: "{{ alerta_discord_webhook_url }}"
