---
ipam:
  mode: kubernetes
kubeProxyReplacement: true
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
k8sServiceHost: localhost
k8sServicePort: 7445
ingressController:
  enabled: {{ cilium_ingress_controller_enabled | lower }}
  loadbalancerMode: {{ cilium_ingress_loadbalancer_mode }}
  default: {{ cilium_ingress_default | lower }}
gatewayAPI:
  enabled: {{ cilium_gateway_api_enabled | lower }}
  enableAlpn: false
  enableAppProtocol: false
l2announcements:
  enabled: {{ cilium_l2_announcements_enabled | lower }}
operator:
  replicas: {{ cilium_operator_replicas }}
externalIPs:
  enabled: {{ cilium_external_ips_enabled | lower }}
devices: {{ cilium_devices }}
