---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # Git repo source for Redis CRD manifest
  source:
    repoURL: https://github.com/jpuskar/ansible_docker_plex
    targetRevision: zfs-disk-replace
    path: argocd-apps/harbor
    directory:
      include: 'redis-standalone.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor

  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
