---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-rawfile-storageclass
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/jpuskar/ansible_docker_plex
    targetRevision: zfs-disk-replace
    path: argocd-apps/openebs-rawfile
    directory:
      include: 'storageclass.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: openebs-rawfile

  syncPolicy:
    # Manual sync only - no automated deployment
    # automated:
    #   prune: true
    #   selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
