---
#- name: ensure nic enp3s4f0 is set to come up on boot
#  lineinfile:
#    path: /etc/sysconfig/network-scripts/ifcfg-enp3s4f0
#    regexp: '^ONBOOT'
#    line: 'ONBOOT=yes'
#- name: ensure nic enp3s4f1 is set to come up on boot
#  lineinfile:
#    path: /etc/sysconfig/network-scripts/ifcfg-enp3s4f1
#    regexp: '^ONBOOT'
#    line: 'ONBOOT=yes'

- name: nic_team | install nmcli deps
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
   - epel-release
   - NetworkManager-glib-devel
   - libnm-gtk-devel
   - nm-connection-editor
   - libsemanage-python
   - policycoreutils-python

- name: nic_team | try nmcli add team - conn_name only & ip4 gw4
  nmcli:
    type: team
    conn_name: '{{ item.conn_name }}'
    ip4: '{{ item.ip4 }}'
    gw4: '{{ item.gw4 }}'
    dns4: '8.8.8.8'
    state: present
  with_items:
    - '{{ nmcli_team }}'

- name: nic_team | try nmcli add teams-slave
  nmcli:
    type: team-slave
    conn_name: '{{ item.conn_name }}'
    ifname: '{{ item.ifname }}'
    master: '{{ item.master }}'
    state: present
  with_items:
    - '{{ nmcli_team_slave }}'

- name: nic_team | up primary team
  shell: nmcli c up team0
