version: "3.7"
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.dockerfile
    container_name: jenkins
#    user: "2022:2022"
    ports:
      - "8080:8080"
    environment:
      - TZ=America/New_York
      - PUID=2023
      - PGID=2023
    networks:
      - jenkins
    volumes:
      - "/docker/nfs_mount/jenkins/jenkins_home:/var/jenkins_home:Z"

# proxy:
#    dockerfile: nginx.dockerfile
#    container_name: proxy
#    restart: unless-stopped
#    ports:
#      - "4444:8080"
#    depends_on:
#      - jenkins
#    networks:
#      - jenkins


networks:
  jenkins:
