---
- name: container | create /etc/docker/compose folder
  file:
    state: directory
    owner: root
    group: root
    path: /etc/docker/compose

- name: "container | create /etc/docker/compose/{{ service_name }} folder"
  file:
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
    path: "/etc/docker/compose/{{ service_name }}"

- name: "container | copy {{ service_name }} dockerfile"
  template:
    src: templates/docker_service.dockerfile
    dest: "/etc/docker/compose/{{ service_name }}/{{ service_name }}.dockerfile"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"

- name: container | check for docker network traefik_outside-world
  shell:
    cmd: docker network ls | grep traefik_outside-world
  register: docker_networks
  changed_when: false
  ignore_errors: yes

- name: container | create docker network traefik_outside-world
  shell:
    cmd: docker network create traefik_outside-world
  when: docker_networks.rc != 0

- name: container | copy docker-compose file
  template:
    src: templates/docker-compose.yml
    dest: "/etc/docker/compose/{{ service_name }}/docker-compose.yml"
    mode: 0644
    owner: root
    group: root

- name: container | copy traefik_dynamic.toml file
  copy:
    src: traefik_dynamic.toml
    dest: "/docker/nfs_mount/{{ service_name }}/traefik_dynamic.toml"
    owner: "{{ service_user }}"
    group: "{{ service_group }}"

- name: container | install systemd unit file
  template:
    src: templates/docker_service.service
    dest: "/etc/systemd/system/{{ service_name }}.service"
    mode: 0755
    owner: root
    group: root

- name: container | reload systemd units
  systemd:
    daemon_reload: yes
